openapi: 3.0.2
info:
  title: Unicomer APP
  description: "Java code example"
  contact:
    email: s.bustospi@gmail.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 0.0.1-SNAPSHOT
paths:
  /pharmacies/{city}:
    get:
      tags:
        - pharmacies
      summary: Get pharmacy by city name
      operationId: getPharmaciesByCity
      parameters:
        - name: city
          in: path
          description: 'The name of city needs to be fetched. '
          required: true
          schema:
            type: string
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Pharmacy'
            application/xml:
              schema:
                $ref: '#/components/schemas/PharmaciesInfo'
        404:
          description: Pharmacies does not found
          content: {}
components:
  schemas:
    Pharmacy:
      type: object
      properties:
        name:
          type: string
        adress:
          type: string
        phone:
          type: string
        latitude:
          type: string
        longitude:
          type: string
      xml:
        name: Pharmacy
    PharmaciesInfo:
      type: array
      items:
        $ref: '#/components/schemas/Pharmacy'
      xml:
        name: Pharmacies
        wrapped: true
